### ISSUE TITLE
Ersetzung von &männlich%weiblich& funktioniert im Serienbrief nicht

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild-NRW-Reports#33]
In den Serienbriefen funktioniert die Ersetzung von &männlicheForm%weiblicheForm& nur, wenn man im Ereignis onMailMerge den Befehl Brieftext.Richtext:=ReplaceDefault(Brieftext.Richtext); ergänzt.

**Comment by Raffenberg** [comment]
Hallo Anne, danke für den Hinweis. Ich habe den Befehl ReplaceDefault in 'DetailBeforPrint' untergebracht, um die Code nicht zu sehr zu verteilen. Dort werden auch die Platzhalter ersetzt.
